[package]
name = "visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
rustfft = "6.2.0"
ratatui = { version = "0.27.0", features = ["all-widgets"] }
crossterm = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
